server:
  port: 9000

# configure name of the service
spring:
  application:
    name: EVENT-SERVICE

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true #default is also true
    service-url:
      defaultZone: http://localhost:8761/eureka